version: "3.9"

services:
  db:
    image: postgres:15  # Postgres version
    container_name: tola_ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # change for prod
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: tola_ecommerce_app
    restart: always
    env_file: .env
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app  # optional for dev hot reload

volumes:
  db_data:
